export const BINGO_ITEMS = [
  { id: 1, label: "Chupete", icon: "🍼" },
  { id: 2, label: "Mamadera", icon: "🥛" },
  { id: 3, label: "Pañal", icon: "🧷" },
  { id: 4, label: "Cochecito", icon: "🛒" },
  { id: 5, label: "Babero", icon: "🧣" },
  { id: 6, label: "Osito", icon: "🧸" },
  { id: 7, label: "Sonajero", icon: "🔔" },
  { id: 8, label: "Cuna", icon: "🛏️" },
  { id: 9, label: "Body", icon: "👕" },
  { id: 10, label: "Zapatitos", icon: "👟" },
  { id: 11, label: "Gorrito", icon: "🧢" },
  { id: 12, label: "Cigüeña", icon: "🦢" },
  { id: 13, label: "Test", icon: "⏸️" },
  { id: 14, label: "Ecografía", icon: "🖼️" },
  { id: 15, label: "Antojos", icon: "🍕" },
  { id: 16, label: "Padrino", icon: "🕶️" },
  { id: 17, label: "Madrina", icon: "👠" },
  { id: 18, label: "Abuela", icon: "👵" },
  { id: 19, label: "Abuelo", icon: "👴" },
  { id: 20, label: "Hermanito/a", icon: "👶" },
  { id: 21, label: "Rosa", icon: "🩷" },
  { id: 22, label: "Azul", icon: "💙" },
  { id: 23, label: "Pastel", icon: "🎂" },
  { id: 24, label: "Regalo", icon: "🎁" },
  { id: 25, label: "Globo", icon: "🎈" },
];
